name: KING SAQR FINAL BUILD
on: 
  workflow_dispatch: # هذا السطر هو مفتاح الحل للتشغيل اليدوي
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Buildozer
        run: |
          sudo apt-get update
          pip3 install --user buildozer cython
      - name: Create APK
        run: |
          yes | /home/runner/.local/bin/buildozer android debug
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: KING-SAQR-APP
          path: bin/*.apk
